#define h "h"
#define hh int
#define hhh main
#define hhhh (
#define hhhhh )
#define hhhhhh {
#define hhhhhhh }
#define hhhhhhhh for
#define hhhhhhhhh ;
#define hhhhhhhhhh printf
#define hhhhhhhhhhh return
#define hhhhhhhhhhhh on_exit
#define hhhhhhhhhhhhh [
#define hhhhhhhhhhhhhh ]
#define hhhhhhhhhhhhhhh 0
